From c55552b32d58e678eb860f8dca161c984e2eeec8 Mon Sep 17 00:00:00 2001
From: Robert Kuska <rkuska@redhat.com>
Date: Thu, 10 Mar 2016 10:08:17 +0100
Subject: [PATCH] Add better error message when trying file is passed

---
 virtualenv.py | 4 ++++
 1 file changed, 4 insertions(+)

diff --git a/virtualenv.py b/virtualenv.py
index 353ed73..4ec3961 100755
--- a/virtualenv.py
+++ b/virtualenv.py
@@ -791,6 +791,10 @@ def main():
         sys.exit(2)
 
     home_dir = args[0]
+    if os.path.exists(home_dir) and os.path.isfile(home_dir):
+        logger.fatal('ERROR: File already exists and is not a directory.')
+        logger.fatal('Please provide a different path or delete the file.')
+        sys.exit(3)
 
     if os.environ.get('WORKING_ENV'):
         logger.fatal('ERROR: you cannot run virtualenv while in a workingenv')
-- 
2.5.0

